-- Add more food items for better variety
-- This migration adds more vegetarian and non-vegetarian options

-- Clear existing food items to start fresh
DELETE FROM public.food_items;

-- Insert comprehensive food items with realistic Indian pricing
INSERT INTO public.food_items (name, calories_per_100g, cost_per_100g_rupees, is_veg, category) VALUES

-- VEGETARIAN COMPLETE MEALS
('🍛 Dal Rice (Lentil Curry with Rice)', 180, 8, true, 'complete_meal'),
('🍛 Rajma Rice (Kidney Bean Curry with Rice)', 195, 10, true, 'complete_meal'),
('🍛 Chana Masala with Rice', 185, 9, true, 'complete_meal'),
('🍛 Aloo Gobi with Roti', 165, 7, true, 'complete_meal'),
('🍛 Palak Paneer with Rice', 220, 12, true, 'complete_meal'),
('🍛 Matar Paneer with Rice', 210, 11, true, 'complete_meal'),
('🍛 Chole Bhature', 350, 18, true, 'complete_meal'),
('🍛 Aloo Paratha with Curd', 280, 8, true, 'complete_meal'),
('🍛 Paneer Paratha with Pickle', 300, 12, true, 'complete_meal'),
('🍛 Dal Makhani with Rice', 200, 15, true, 'complete_meal'),
('🍛 Chana Dal with Rice', 175, 6, true, 'complete_meal'),
('🍛 Moong Dal with Rice', 170, 5, true, 'complete_meal'),
('🍛 Sambar Rice', 160, 7, true, 'complete_meal'),
('🍛 Rasam Rice', 140, 6, true, 'complete_meal'),
('🍛 Vegetable Biryani', 240, 12, true, 'complete_meal'),
('🍛 Pulao (Mixed Vegetable)', 200, 10, true, 'complete_meal'),
('🍛 Jeera Rice with Dal', 180, 8, true, 'complete_meal'),
('🍛 Lemon Rice with Papad', 160, 6, true, 'complete_meal'),
('🍛 Coconut Rice with Curry', 190, 9, true, 'complete_meal'),
('🍛 Tamarind Rice with Pickle', 170, 7, true, 'complete_meal'),

-- NON-VEGETARIAN COMPLETE MEALS
('🍛 Chicken Curry with Rice', 210, 15, false, 'complete_meal'),
('🍛 Mutton Curry with Rice', 250, 18, false, 'complete_meal'),
('🍛 Fish Curry with Rice', 190, 16, false, 'complete_meal'),
('🍛 Egg Curry with Rice', 200, 8, false, 'complete_meal'),
('🍛 Prawn Curry with Rice', 180, 20, false, 'complete_meal'),
('🍛 Chicken Biryani', 280, 20, false, 'complete_meal'),
('🍛 Mutton Biryani', 320, 25, false, 'complete_meal'),
('🍛 Fish Biryani', 260, 22, false, 'complete_meal'),
('🍛 Egg Biryani', 240, 12, false, 'complete_meal'),
('🍛 Chicken Pulao', 220, 16, false, 'complete_meal'),
('🍛 Mutton Pulao', 260, 20, false, 'complete_meal'),
('🍛 Chicken Fried Rice', 250, 18, false, 'complete_meal'),
('🍛 Egg Fried Rice', 200, 10, false, 'complete_meal'),
('🍛 Chicken Tikka with Rice', 230, 22, false, 'complete_meal'),
('🍛 Tandoori Chicken with Rice', 240, 25, false, 'complete_meal'),
('🍛 Butter Chicken with Rice', 280, 24, false, 'complete_meal'),
('🍛 Chicken Masala with Rice', 220, 18, false, 'complete_meal'),
('🍛 Mutton Masala with Rice', 260, 22, false, 'complete_meal'),
('🍛 Fish Masala with Rice', 200, 20, false, 'complete_meal'),
('🍛 Prawn Masala with Rice', 190, 24, false, 'complete_meal'),

-- VEGETARIAN BREAKFAST
('🥞 Masala Dosa', 180, 15, true, 'breakfast'),
('🥞 Plain Dosa', 160, 12, true, 'breakfast'),
('🥞 Onion Dosa', 170, 13, true, 'breakfast'),
('🥞 Rava Dosa', 175, 14, true, 'breakfast'),
('🥞 Idli (2 pieces)', 120, 8, true, 'breakfast'),
('🥞 Vada (2 pieces)', 200, 10, true, 'breakfast'),
('🥞 Upma', 140, 6, true, 'breakfast'),
('🥞 Poha', 130, 5, true, 'breakfast'),
('🥞 Paratha (Aloo)', 250, 8, true, 'breakfast'),
('🥞 Paratha (Paneer)', 280, 12, true, 'breakfast'),
('🥞 Paratha (Gobi)', 240, 7, true, 'breakfast'),
('🥞 Paratha (Onion)', 230, 6, true, 'breakfast'),
('🥞 Bread Butter', 200, 4, true, 'breakfast'),
('🥞 Bread Jam', 180, 3, true, 'breakfast'),
('🥞 Cornflakes with Milk', 120, 5, true, 'breakfast'),
('🥞 Oats with Milk', 110, 4, true, 'breakfast'),
('🥞 Muesli with Milk', 150, 8, true, 'breakfast'),
('🥞 Poha with Peanuts', 160, 7, true, 'breakfast'),
('🥞 Upma with Vegetables', 170, 8, true, 'breakfast'),
('🥞 Besan Chilla', 180, 6, true, 'breakfast'),

-- NON-VEGETARIAN BREAKFAST
('🥞 Egg Dosa', 200, 14, false, 'breakfast'),
('🥞 Chicken Dosa', 220, 18, false, 'breakfast'),
('🥞 Egg Paratha', 280, 10, false, 'breakfast'),
('🥞 Chicken Paratha', 300, 15, false, 'breakfast'),
('🥞 Egg Sandwich', 250, 12, false, 'breakfast'),
('🥞 Chicken Sandwich', 280, 16, false, 'breakfast'),
('🥞 Egg Bhurji with Bread', 220, 8, false, 'breakfast'),
('🥞 Chicken Bhurji with Bread', 240, 12, false, 'breakfast'),
('🥞 Omelette with Bread', 200, 9, false, 'breakfast'),
('🥞 Scrambled Eggs with Toast', 180, 7, false, 'breakfast'),

-- VEGETARIAN SNACKS
('🥟 Samosa (2 pieces)', 300, 8, true, 'snacks'),
('🥟 Kachori (2 pieces)', 320, 10, true, 'snacks'),
('🥟 Pakora (Mixed)', 280, 12, true, 'snacks'),
('🥟 Vada Pav', 250, 8, true, 'snacks'),
('🥟 Pav Bhaji', 220, 15, true, 'snacks'),
('🥟 Chole Bhature', 350, 18, true, 'snacks'),
('🥟 Momos (6 pieces)', 200, 12, true, 'snacks'),
('🥟 Spring Roll (2 pieces)', 180, 10, true, 'snacks'),
('🥟 Cutlet (2 pieces)', 200, 8, true, 'snacks'),
('🥟 Aloo Tikki (2 pieces)', 180, 6, true, 'snacks'),
('🥟 Pani Puri (6 pieces)', 150, 8, true, 'snacks'),
('🥟 Bhel Puri', 160, 10, true, 'snacks'),
('🥟 Sev Puri (6 pieces)', 170, 12, true, 'snacks'),
('🥟 Dahi Puri (6 pieces)', 140, 10, true, 'snacks'),
('🥟 Ragda Pattice', 200, 12, true, 'snacks'),
('🥟 Masala Puri', 180, 9, true, 'snacks'),
('🥟 Chaat (Mixed)', 190, 11, true, 'snacks'),
('🥟 Dhokla (4 pieces)', 120, 8, true, 'snacks'),
('🥟 Khandvi (6 pieces)', 100, 10, true, 'snacks'),
('🥟 Handvo (2 pieces)', 150, 7, true, 'snacks'),

-- NON-VEGETARIAN SNACKS
('🥟 Chicken Momos (6 pieces)', 220, 15, false, 'snacks'),
('🥟 Mutton Momos (6 pieces)', 240, 18, false, 'snacks'),
('🥟 Chicken Cutlet (2 pieces)', 250, 12, false, 'snacks'),
('🥟 Fish Cutlet (2 pieces)', 230, 14, false, 'snacks'),
('🥟 Chicken Tikka (4 pieces)', 200, 20, false, 'snacks'),
('🥟 Tandoori Chicken (2 pieces)', 180, 25, false, 'snacks'),
('🥟 Chicken Wings (4 pieces)', 220, 18, false, 'snacks'),
('🥟 Fish Fingers (4 pieces)', 190, 16, false, 'snacks'),
('🥟 Prawn Cutlet (2 pieces)', 210, 22, false, 'snacks'),
('🥟 Egg Roll', 180, 8, false, 'snacks'),
('🥟 Chicken Roll', 200, 12, false, 'snacks'),
('🥟 Mutton Roll', 220, 15, false, 'snacks'),
('🥟 Fish Roll', 190, 14, false, 'snacks'),
('🥟 Chicken Sandwich', 250, 15, false, 'snacks'),
('🥟 Egg Sandwich', 200, 10, false, 'snacks'),
('🥟 Chicken Burger', 280, 20, false, 'snacks'),
('🥟 Fish Burger', 260, 18, false, 'snacks'),
('🥟 Chicken Wrap', 220, 16, false, 'snacks'),
('🥟 Egg Wrap', 180, 12, false, 'snacks'),
('🥟 Chicken Pizza Slice', 300, 25, false, 'snacks'),

-- VEGETARIAN BEVERAGES
('🥤 Tea', 5, 2, true, 'beverages'),
('🥤 Coffee', 8, 3, true, 'beverages'),
('🥤 Lassi (Sweet)', 80, 8, true, 'beverages'),
('🥤 Lassi (Salty)', 60, 6, true, 'beverages'),
('🥤 Fresh Juice (Orange)', 45, 12, true, 'beverages'),
('🥤 Fresh Juice (Apple)', 50, 10, true, 'beverages'),
('🥤 Fresh Juice (Pomegranate)', 55, 15, true, 'beverages'),
('🥤 Coconut Water', 20, 8, true, 'beverages'),
('🥤 Buttermilk', 40, 3, true, 'beverages'),
('🥤 Soft Drink (Coke/Pepsi)', 42, 5, true, 'beverages'),
('🥤 Green Tea', 2, 3, true, 'beverages'),
('🥤 Lemonade', 30, 6, true, 'beverages'),
('🥤 Jaljeera', 25, 4, true, 'beverages'),
('🥤 Aam Panna', 35, 8, true, 'beverages'),
('🥤 Nimbu Pani', 20, 3, true, 'beverages'),
('🥤 Chaas', 30, 4, true, 'beverages'),
('🥤 Badam Milk', 120, 15, true, 'beverages'),
('🥤 Kesar Milk', 100, 12, true, 'beverages'),
('🥤 Rose Milk', 90, 10, true, 'beverages'),
('🥤 Thandai', 80, 8, true, 'beverages'),

-- VEGETARIAN DESSERTS
('🍰 Gulab Jamun (2 pieces)', 320, 8, true, 'desserts'),
('🍰 Rasgulla (3 pieces)', 150, 6, true, 'desserts'),
('🍰 Kheer (Rice Pudding)', 120, 8, true, 'desserts'),
('🍰 Halwa (Carrot)', 280, 10, true, 'desserts'),
('🍰 Halwa (Semolina)', 300, 8, true, 'desserts'),
('🍰 Jalebi (4 pieces)', 350, 12, true, 'desserts'),
('🍰 Ladoo (2 pieces)', 280, 6, true, 'desserts'),
('🍰 Barfi (2 pieces)', 320, 8, true, 'desserts'),
('🍰 Ice Cream (Vanilla)', 200, 10, true, 'desserts'),
('🍰 Ice Cream (Chocolate)', 220, 12, true, 'desserts'),
('🍰 Kulfi (2 pieces)', 180, 8, true, 'desserts'),
('🍰 Rasmalai (2 pieces)', 160, 10, true, 'desserts'),
('🍰 Sandesh (4 pieces)', 140, 12, true, 'desserts'),
('🍰 Peda (2 pieces)', 200, 8, true, 'desserts'),
('🍰 Modak (4 pieces)', 150, 10, true, 'desserts'),
('🍰 Malpua (2 pieces)', 250, 8, true, 'desserts'),
('🍰 Rabri', 180, 12, true, 'desserts'),
('🍰 Phirni', 160, 10, true, 'desserts'),
('🍰 Gajar Halwa', 220, 12, true, 'desserts'),
('🍰 Sooji Halwa', 200, 6, true, 'desserts'),

-- VEGETARIAN FAST FOOD
('🍔 Veg Burger', 250, 15, true, 'fast_food'),
('🍟 French Fries', 365, 8, true, 'fast_food'),
('🍕 Pizza (Veg)', 266, 18, true, 'fast_food'),
('🌮 Tacos (2 pieces)', 200, 12, true, 'fast_food'),
('🌯 Wrap (Veg)', 180, 10, true, 'fast_food'),
('🍝 Pasta (Veg)', 150, 12, true, 'fast_food'),
('🍜 Noodles (Veg)', 140, 10, true, 'fast_food'),
('🥗 Salad (Mixed)', 80, 8, true, 'fast_food'),
('🥪 Sandwich (Veg)', 200, 12, true, 'fast_food'),
('🌭 Hot Dog (Veg)', 180, 10, true, 'fast_food'),

-- NON-VEGETARIAN FAST FOOD
('🍔 Chicken Burger', 280, 20, false, 'fast_food'),
('🍕 Pizza (Chicken)', 290, 22, false, 'fast_food'),
('🌮 Chicken Tacos (2 pieces)', 220, 15, false, 'fast_food'),
('🌯 Wrap (Chicken)', 200, 12, false, 'fast_food'),
('🍝 Pasta (Chicken)', 170, 15, false, 'fast_food'),
('🍜 Noodles (Chicken)', 160, 12, false, 'fast_food'),
('🥪 Sandwich (Chicken)', 220, 14, false, 'fast_food'),
('🌭 Hot Dog (Chicken)', 200, 12, false, 'fast_food'),
('🍗 Fried Chicken (2 pieces)', 300, 18, false, 'fast_food'),
('🍖 Chicken Nuggets (6 pieces)', 250, 16, false, 'fast_food');

-- Update the food items data in the frontend file as well
-- This will be handled by the frontend data file update
