// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkkpwapwnolkyugmopuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxra3B3YXB3bm9sa3l1Z21vcHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDE4NTYsImV4cCI6MjA3MzMxNzg1Nn0.xl4MNiB3ImLyz9WO4PtVJUjMQCnI3VN75YqOnFKdCmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});